### ISSUE TITLE
Service slots aren't copied to clipboard

### ISSUE THREAD

**Issue by a-klimashevsky** [pyfa-org/Pyfa#1362]
## Bug Report

Service slots cannot be copied to clipboard

### Expected behavior:

Service slots copied with another modules

### Actual behavior:

All modules except service slots are copied

### Detailed steps to reproduce:

1) Fit any structure with service slots
2) Copy fit to clipboard using any method (eft or multybuy)
3) Look at a list of modules

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Athanor, Athanor fit]

Standup Ballistic Control System I

Standup Stasis Webifier I
Standup Warp Scrambler I
Standup Target Painter I

Standup ASML Missile Launcher I, Standup ASML-LD Missile
Standup Heavy Energy Neutralizer I
Standup Heavy Energy Neutralizer I

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:

Arms Race 1.3 - v1.34.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

OS X 10.12.6

**Comment by blitzmann** [comment]
Thanks for the report, this really should be an easy fix seems like an
oversight on what is exported and what is not.  Will take a look

**Comment by burnsypet** [comment]
I have fixed this, in port.py Slot.SERVICE was not defined in the EFT slot order list.

For a similar reason it looks like trying to export a citadel crest fitting also fails. This is because Slot.SERVICE is not defined in INV_FLAGS, however I do not know what flag service modules use and cannot find any documentation on int @blitzmann could you suggest anywhere I can find that information? If so I can fix both issues at once. Cheers.

**Comment by blitzmann** [comment]
Yep, I also had this partially fixed but had to wait to get the inv flags. I believe they are in the SDE in a file called `invFlags.yaml` or something - if you can't find them let me know and I can look. IIRC, the flag in pyfa is supposed to be the first flag representing that slot (so if hi slots are flags 10-18, pyfa needs 10 and it should be able to extrapolate from there)

That would be sweet if you can send a PR for the fix as I'm tied up with RL atm :)
