### ISSUE TITLE
Character editor consistency improvements

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1886]
(or, actually, fixes)

* [x] Categories of skills are not expanded by double-clicking on them
* [x] Editor window itself is treated as separate window which has significant usability loss under gnome 3 (shown as separate application in alt-tab menu, various focus loss and z-order bugs on attempts to open skill stats and close them).

**Comment by DarkFenX** [comment]
I fixed 3) in 52a68adb11d52de859914f29ccb325fd132233f9, but 1st two might need (a little) more work than that. I tried embedding
```
        if "__WXGTK__" in wx.PlatformInfo:
            self.Bind(wx.EVT_RIGHT_UP, self.scheduleMenu)
        else:
            self.Bind(wx.EVT_RIGHT_DOWN, self.scheduleMenu)
```
there but it did not work right away.

**Comment by blitzmann** [comment]
Pushed a fix for 2 (haven't tested on Linux yet). It's amazing we didn't have that.

1) is very weird... haven't had a chance to look into it. The fix you propose... I think we use something similar somewhere else (where GTK handles on up rather than down).

**Comment by blitzmann** [comment]
As for your fix for 3 - I think the character editor used to be a Dialog, so wasn't considered another frame. The dialog had some issues with os x back when we upgraded to wxPython 3 way back when. Might be good to look at it again though

**Comment by DarkFenX** [comment]
Now it seems to have some column width issues, similar to item attributes window:

![image](https://user-images.githubusercontent.com/275209/54584831-78a98180-4a29-11e9-9b28-4987a620f32a.png)

In this case though i believe we can set width manually (in percents, maybe we can make it resizable later).

**Comment by DarkFenX** [comment]
As for dialog or not - it completely depends on our desire to block the rest of the UI while the editor is open. However, it might interfere with some use-cases, e.g. it's possible to open skill stats windows and keep them after the editor is closed, how will dialog affect it?

**Comment by blitzmann** [comment]
So before adding that event, the column was sized correctly? Odd. They dont even use the same control.  Hrm...

**Comment by blitzmann** [comment]
Just checked on ubuntu - seems the column cutoff was already an before the fix for double click.

Since the character editor is a fixed size, will set first column to fixed size as well. That should at least clear the issue for now.

**Comment by blitzmann** [comment]
Okay, columns should be fixed (haven't check wayland, but on windows and ubuntu xorg looks better).

We should probably consider converting the skill tree to HyperTreeList, same as attributes use. The benefit of doing that is that the code behind it is all python, so we can change the functionality if needed. It's a bit more difficult do that that for TreeListCtrl, and it's generally confusing since the two share a very similar API but slightly different functionality

**Comment by DarkFenX** [comment]
Looks good on wayland now, thanks! Only right click issue remains now.

**Comment by DarkFenX** [comment]
Moved right-click issue to separate ticket
