### ISSUE TITLE
Crash on opening fit / searching market

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#598]
Some folks are experiencing random crashes in Windows. If you're experiencing these issues, please post here and subscribe to the thread - I may have you try to test a few things.

EDIT:
- Crashes happen with the Citadel Pre Release. v1.20.1 is unaffected.

WORKAROUND:
- Running pyfa in administrator mode fixes the crashes according to some users. 0.o

**Comment by IndianaJars** [comment]
Crashes within 10 Seconds of opening a fit, tried different fits, tried uninstalling and reinstalling

**Comment by Zagor24** [comment]
I've been experiencing crashes as well. Every time i open an already fitted ship, or if i try to fit modules on a blank fit, the client crashes. 
If i open a new fit with no modules, the client remains stable, i can check ship stats, change character profiles etc... but as soon as i open some module category in the market section and look at individual modules, it crashes.
I know for a fact that it started out of the blue, before i installed the citadel update. Previous version was working fine, then i havent used it for some time, and wanted to check something around the time citadel went live, and it started crashing. I thought updating to the latest version would fix it (i even deleted the client completely, and made a fresh install), but it didnt help.

**Comment by blitzmann** [comment]
Did you guys try the Citadel pre-release? If so, were you experiencing crashes on that build? If you haven't, please download and test it out (on the Releases page) - it should use a separate test database so you current fits shouldn't be affected.

**Comment by locten** [comment]
can confirm importing a fit crashes both Preview: Character Implants build and singularity-1027729: Citadel Pre-Release build after around 5-10 seconds.

**Comment by aran-hotchkiss** [comment]
Someone commented on the EvE-o forums about running the program in administrator mode....
I tried that and it seems to have resolved all issues for me - hasn't crashed once since I did that. Suggest you fellas try it and see if it works.

**Comment by locten** [comment]
ok so apparently running as admin fixed the problem could have sworn i had already tried that its usually the 1st thing i try if something crashes but guess i dident.

**Comment by blitzmann** [comment]
What the literal fuck... That makes no sense. BUT, but gives me more information so yay. Updating the OP

**Comment by Zagor24** [comment]
Confirmed, its working in admin mode.

**Comment by blitzmann** [comment]
Can you guys try the Character Implant Preview and let me know if that build crashes?

https://github.com/pyfa-org/Pyfa/releases/tag/preview_char_implants

**Comment by blitzmann** [comment]
Also, take a peek in event viewer and post the info it has on pyfa:

Quick and dirty: http://www.cyberlink.com/support/faq-content.do?id=10449

**Comment by Zagor24** [comment]
Here's the info from the Even Viewer:

Faulting application name: pyfa.exe, version: 1.15.1.0, time stamp: 0x549debdc
Faulting module name: COMCTL32.dll, version: 6.10.10586.0, time stamp: 0x5632d2bf
Exception code: 0xc000041d
Fault offset: 0x0007dc89
Faulting process id: 0x2848
Faulting application start time: 0x01d1a5c88c324ce4
Faulting application path: C:\Program Files (x86)\pyfa\pyfa.exe
Faulting module path: C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.10586.0_none_d3c2e4e965da4528\COMCTL32.dll
Report Id: 4fb54582-797e-464e-8c69-24641e8f45fb
Faulting package full name: 
Faulting package-relative application ID:

**Comment by blitzmann** [comment]
@zagor thanks. Can you also try the character implant preview release and let me know if that crashes as well? I'm just trying to narrow down which changes may have caused the offending crash

**Comment by locten** [comment]
so i tried the character implant preview and it dident crash opened event viewer to try and get that for you turned auto use admin mode off and now it docent crash even if i don't run as admin...

**Comment by locten** [comment]
even deleting all associated files and reinstalling and running without admin it docent crash any more so im super confused now lol

**Comment by ullerrm** [comment]
One reproducable crash: Open a fit in a tab, then delete the fit from the Ships pane.

**Comment by blitzmann** [comment]
For those experiencing the crash, please send me your database file (`%userprofile%/.pyfa/saveddata.db`). Email is in README. 

Can I get others to confirm that it doesn't crash when running the character preview build? Getting more confirmation will help narrow it down.

@ullerrm that is a different issue that's been known about. See #164

**Comment by blitzmann** [comment]
Can anyone else confirm the above?

**Comment by digitalwolf** [comment]
I have the crash, even in the preview build, unless I run as administrator.

**Comment by ErinOswell** [comment]
Confirming this; crashes when I have a fitting open and search for a module in market tab, oddly it works fine searching in the market tab with no fittings open. Will try running as admin

**Comment by Ecnav** [comment]
I am having the exact same issue as ErinOswell and running as administrator seems to have worked for me as well.

**Comment by mrnsnp** [comment]
Crash occurs shortly after I switch over to market tab to start ship fitting. Win10 Pro

•System 
◦Provider 
[ Name] Windows Error Reporting 
◦EventID 1001 
[ Qualifiers] 0 
Level 4 
Task 0 
Keywords 0x80000000000000 
◦TimeCreated 
[ SystemTime] 2016-05-07T15:42:19.247618900Z 
EventRecordID 1255 
Channel Application 
Computer DELLONE-PC 
Security 
•EventData 
108127056753 
 1 
 APPCRASH 
 Not available 
 0 
 pyfa.exe 
 1.15.1.0 
 549debdc 
 COMCTL32.dll 
 6.10.10586.0 
 5632d2bf 
 c0000005 
 0007dc89 
C:\Users\DELL ONE\AppData\Local\Temp\WER4EA7.tmp.WERInternalMetadata.xml 
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_pyfa.exe_cb32231e4999c411fdf6dbbd71d651675f20ab_971b30ad_dd577048 
0 
 169a3bf8-4255-46ae-84e9-6e9d5da189e4 
 0 
 3a41bcf74eaf715fbe0cecd144234446

**Comment by blitzmann** [comment]
@digitalwolf when you say preview release, do you mean the citadel preview or the character implant preview? 
I want to make sure that the crash is / is not happening with this one: https://github.com/pyfa-org/Pyfa/releases/tag/preview_char_implants

**Comment by aaronmallen** [comment]
+1

**Comment by blitzmann** [comment]
Alright guys, I have a favor to ask of you. Can you please download and run each of these build and note if the crashing happens? Try each build two or three times. Make sure they stay seperate (do not overwrite one build install with another, keep them separate after extracting).

When done, please post results here (which builds worked, which builds failed. Each build archive is prefixed with a number that you can use to identify each one). This is extremely important in trying to narrow down which change causes the crashing, because after looking through the relevant code there is not reason to require admin privileges. 

It should also be noted that these builds should be using their own test database, so it shouldn't affect your user user database with fits.

http://dl.eve-files.com/media/1605/1-pyfa-20160508-dc55db-win.zip
http://dl.eve-files.com/media/1605/2-pyfa-20160508-ca34d7-win.zip
http://dl.eve-files.com/media/1605/3-pyfa-20160508-48b45b-win.zip
http://dl.eve-files.com/media/1605/4-pyfa-20160508-443c91-win.zip
http://dl.eve-files.com/media/1605/5-pyfa-20160508-80e47d-win.zip
http://dl.eve-files.com/media/1605/6-pyfa-20160508-ca91f6-win.zip
http://dl.eve-files.com/media/1605/7-pyfa-20160508-0d41cb-win[1].zip

**Comment by Aarondorn2** [comment]
Also happening for me about 10-20 seconds after launching the app.  Tried uninstalling, reinstalling, previous versions, different fits, etc.

**Comment by blitzmann** [comment]
What do you mean by different versions? Others have stated that 1.20 seems to work. Is that not the case for you? Can you also look at my previous comments and test out those builds that I provided

**Comment by TeophanuTivianne** [comment]
First of all - I get the constant crashes in 1.21, but only if I remove modules from a fit or close a few tabs with fits in them, or open the settings (unless I delete the settings folder, in which case this is not an issue), this is all fixed by running the app in admin mode. 1.20 crashes the second I start it up for me.

Now (for whatever reason) even my main Pyfa install (latest release) crashes as soon as I open it, unless run as admin.

For the 7 builds:
None of those builds work for me.
Build 1 complains that it can't find module "pyfa_main_" and doesn't start at all
Build 2 crashes when I search the market for mods (after a few seconds, but without adding any module to any fits), but ONLY when I actually have a fit open, UNLESS I actually open a module (or whatever) market group, then it crashes even without any open fits. It does however not crash when I remove modules, or open the settings, or close opened fits.
Build 3 behaves (as far as I have tested) just like 2.
Build 4 is basically the same as 2&3 (as far as I can tell)
Build 5 is the same as the ones before
Build 6 exactly as before
Build 7 again the same

I'm on Windows 10, 64 bit.

**Comment by blitzmann** [comment]
So 1.20 doesn't work for you? What is the latest stable released on the releases page that does work for you? I wonder if that's a separate issue as someone said1.20 worked for them... =(

**Comment by Aarondorn2** [comment]
1.20 is not currently working for me; it was working previously without any issues. I installed 1.21, started experiencing the crashes, rolled back to 1.20 and am still experiencing them.  

Thanks for the hard work - this is such an amazing tool.  I'll try the builds listed above.

**Comment by Aarondorn2** [comment]
my results from the builds above: builds 1 & 4 fail to launch (different errors), the rest crash with the same behavior as 1.21 (typically immediately after attempting to fit a module to a ship).

**Comment by blitzmann** [comment]
Can you try, in order,  1.17.1, 1.18,  1.19.1?

It doesn't make any sense to me to have 1.20 work, but not work upon downgrade, unless it's a database issue. Can you mail me your saveddata.db file to the email listed on the readme?

**Comment by blitzmann** [comment]
Also, if you're feeling adventurous:

https://github.com/pyfa-org/Pyfa/wiki/Setting-Up-Development-Environment

Follow those steps to get a very minimal dev environment set up and run pyfa directly from source. This might print out errors that are otherwise lost. All python stuff is contained within the python install directory, so it's easy to uninstall when it's no longer useful (simply delete the directory)

**Comment by Aarondorn2** [comment]
I tried 1.17.1, 18, and 1.19.1 - all same error.  I've been using PYFA for about 7 months, so these versions have worked for me before.

I sent you my saveddata.db - there are also 4 saveddata_migration and a saveddata-test file in that folder.

Thanks!

**Comment by blitzmann** [comment]
Thanks for the info, and the database. =)

The fact the older versions also no longer work makes me believe it's something environmental - something going on with the system. The fact that it started happening with the latest version is curious though. Fuck if I know. 

Honestly I'm out of ideas apart from trying to run pyfa through the python interpreter as before. I'll continue to look around and see if I can find any answers, but for now running as admin may be the only way to resolve this. =/

**Comment by Aarondorn2** [comment]
Thanks for looking into it!

Running as admin hasn't crashed yet!  So I'll use that for now, thanks!

**Comment by mrnsnp** [comment]
Admin level operation works for me. I'm wondering if windows isn't wanting to allow read/write access to database and crashing out. Seams like the most likely culprit as Admin doesn't crash, so its a privilege error.

**Comment by blitzmann** [comment]
I don't understand why though. The user database is written to `~/.pyfa/` which the user should always have write access to. The eve database is installed wherever pyfa is installed - default is Program Files, which is restricted - I can see this happening if we were writing to the EVE DB, but that's not the case as far as I'm aware. We only read from it. And then the fact that this just started happening, and is now apparently being applied retroactively to older versions that never had an issue. I am lost.

It would be nice if there was a way to determine why it needs admin - like what operations is it trying to do that determine it, but I don't know how to test for that.

**Comment by narthollis** [comment]
If it is a file read/write issue then sysinternals process monitor is the
tool to use. Sadly it's a bit involved getting useful info from it.

**Comment by blitzmann** [comment]
@narthollis thanks! I'll try to get that up and running this week and see if I notice anything on my end even if I can't reproduce. Otherwise I may have to put up a little how-to here for others to try.

**Comment by blitzmann** [comment]
As a side note, I really don't believe it is a file read/write issue, considering the error comes from windows CommonControls. I strongly believe this is some sort of error being thrown at the wxWidgets layer (similar to #441)

**Comment by mrnsnp** [comment]
Faulting application name: pyfa.exe, version: 1.15.1.0, time stamp: 0x549debdc
Faulting module name: COMCTL32.dll, version: 6.10.10586.0, time stamp: 0x5632d2bf
Exception code: 0xc0000005
Fault offset: 0x0007dc89
Faulting process id: 0x11e4
Faulting application start time: 0x01d1aae421275b5d
Faulting application path: C:\Users\DELL ONE\Documents\pyfa\pyfa.exe
Faulting module path: C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.10586.0_none_d3c2e4e965da4528\COMCTL32.dll
Report Id: 97a34004-1fbf-4026-b083-494f7e43c399
Faulting package full name: 
Faulting package-relative application ID: 

PYFA is experiencing an access violation in the comctl32.dll on my system if I have a fit loaded and open the market browser.

Figure this site might help you as it lists everything comctl32.dll is linked to in Win10:
http://windows10dll.nirsoft.net/comctl32_dll.html

This is making me want to learn programming

**Comment by blitzmann** [comment]
> This is making me want to learn programming

Please do! It's frustrating at times, but very rewarding if you can solve the problem. :)

Also thanks for the report. Can you guys try to run `sfc /scannow` at an admin command prompt? Apparently theres been some issues online with Explorer.exe crashing with COMCTL32.dll, and this is something frequently suggested. Maybe it will help?

**Comment by mrnsnp** [comment]
I ran sfc /scannow admin lvl on my home computer with no issues found, same crashes as my work laptop which are my earlier posts. I'll run same thing on work laptop and post if it finds a problem. I'm wondering if the issue is somewhere in the stack for GUI.

**Comment by hom3gr0wn** [comment]
Pyfa Loads but when i click on a ship fit it locks up and crashes

**Comment by blitzmann** [comment]
@mrnsnp excellent info. Is there a way to export the results of sysinternals, or take a screenshot with as much relevant info as you can?

Can you also try these versions and tell me if sysinternals gives the same information for the crash:
https://github.com/pyfa-org/Pyfa/releases/tag/v1.17.1
https://github.com/pyfa-org/Pyfa/releases/tag/v1.18.0
https://github.com/pyfa-org/Pyfa/releases/tag/v1.19.1

**Comment by mrnsnp** [comment]
There is however I didn't have my usb drive at work, so anything submitted for the next 36 hrs is going to be based off of my home system. I'll update this post based on relevant info for the listed releases.

**Comment by blitzmann** [comment]
Yeah, whenever you can please provide comprehensive evaluation of the versions listed (as well as current release of course) along with exported data / screenshots. That's the next best thing to being able to reproduce it myself.

**Comment by blitzmann** [comment]
@mrnsnp I see you update your post. I'll take a look at it when I can and go from there. In the future though please make a new post to the thread - I don't receive notifications for post edits like I do for new posts, and it'll be easy to miss. =)

**Comment by blitzmann** [comment]
Update: I also get buffer overflows. However, I don't believe these are errors (see http://superuser.com/questions/491597/process-monitor-entrys-with-buffer-overflow), and I don't think they are related to the problem here (which I would think would happen with or without admin rights).

@mrnsnp you stated that 1.17, 1.18, and 1.19 work fine without admin rights, correct? That contradicts what @Aarondorn2 said in his comment (https://github.com/pyfa-org/Pyfa/issues/598#issuecomment-217764937) so I'm not sure if there's another separate issue there.

I'll be posting to the wxpython group today to see if anyone has any ideas.

**Comment by blitzmann** [comment]
more info: the exception that causes the crash is one of these two:
*  `0xc000041d - STATUS_FATAL_USER_CALLBACK_EXCEPTION`
*  `0xc0000005 - ACCESS VIOLATION`

**Comment by hom3gr0wn** [comment]
Wiped out windows and works fine now I think it's Microsoft maybe a dll file issue

**Comment by SpeedProg** [comment]
I can only tell you one thing if I run it from source there are no problems at all.
your packed files from the downloads crash, so I am pretty sure there is  an issue with the packaging xD

**Comment by blitzmann** [comment]
In that case, I'll try to rebuild the binaries (ugh) and post here for testing.

**Comment by mavu** [comment]
Hi, I know the bug says windows, but I experience the same or something very similar on linux running the current master branch. (since about the citadel release, can't say anything about earlier, only resubbed recently)

There are possibly 2 issues because most of the time it just crashes with "Segmentation fault", but rarely I get some debug info. (don't have it at hand, will update when it happens again.)

Is there any kind of debug mode where I can get more messages out of it, to help debug?
Should I make a Linux-only bugreport seperate from this one?

**Comment by blitzmann** [comment]
@mavu Which distro and version are you using? What version of sqlalchemy? Does this happen with searching the market, fitting the ship, browser fits, etc? Can you please try earlier versions (the latest point releases for 1.19, 1.20) and let me know if they experience the same issue.

**Comment by blitzmann** [comment]
@mavu Also, in `eos/config.py` there is a debug flag. Please set this tie `debug = True` and try again. IIRC, this should enable debugging in sqlalchemy, which should print out the sql statements that it's using. Post that here, it might help.

**Comment by mavu** [comment]
Using fresh debian testing (updated today, last update some month back)
Package: python-sqlalchemy Version: 1.0.12+ds1-1

It happens when fitting modules and selecting fits (feels more rare, but you do that less often, so...). 
here is a pastebin with Debug=True: http://pastebin.com/gmv9jdmx

I am guessing update prices happens in both those cases? A clue?
I'll try the point releases next. is there a way to disable the prices/market stuff?

**Comment by blitzmann** [comment]
Check to see if you have automatic HTML exports enabled in the preferences.

**Comment by mavu** [comment]
Yes, it was enabled, switched off, and it feels carefully optimistic, as it has not crashed since, and I shuffled stuff around, but not long enough to say its stable.

**Comment by blitzmann** [comment]
Please let me know of your outcome. I really should remove the auto HTML export - it's always given us problems.

**Comment by mavu** [comment]
Ok, re-enabled the market updates, left HTML export off. no crash since.
I'd make the automatic HTML export off-by-default, people always complain if you remove features :)

**Comment by MaxHeadRom** [comment]
For about 2 years now Pyfa consistently crashes on me whilst I'm just doing the usual clicking through ships or market items. I've updated with every new release over the years but the same issue remains. I've uninstalled and reinstalled numerous versions. Running as administrator has no effect. The issue occurred in Win 7 and now also in Win 10. I've googled this problem but couldn't find anyone else with exactly the same issue so I've just put it down to a corrupt file somewhere which doesn't get updated/uninstalled/fixed.  I'm kind of getting fed up with it now as I usually have to restart Pyfa a few times in the space of half a hour. If you could help me sort this out I'm be mighty grateful! Cheers.

**Comment by MaxHeadRom** [comment]
My crash report:

Faulting application name: pyfa.exe, version: 1.15.1.0, time stamp: 0x549debdc
Faulting module name: ntdll.dll, version: 10.0.10586.306, time stamp: 0x571afb7f
Exception code: 0xc0000005
Fault offset: 0x00026d79
Faulting process id: 0x307c
Faulting application start time: 0x01d1d810a676768e
Faulting application path: C:\Program Files (x86)\pyfa\pyfa.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: eb74bcb3-6d18-43b1-8fc4-1e25797f0a81
Faulting package full name: 
Faulting package-relative application ID:

**Comment by blitzmann** [comment]
@MaxHeadRom I have never headr of that issue before. The module at fault is `ntdll.dll` which is a core Windows file. I wonder if that file is corrupt. You said it happened on Win7 and Win10, did you by chance upgrade from 7 to 10 or was it a clean install?

**Comment by MaxHeadRom** [comment]
Yeah right.... Windows was upgraded 7 to 10.

**Comment by blitzmann** [comment]
I know it's not ideal, but maybe try a clean install with windows 10.

I have no idea why pyfa is crashing with the module being at fault. Everything I read online points to `ntdll.dll` being corrupted, or something like nvidia driver issues. This is something that I've never seen happen with pyfa, hence why I believe it's localized to your machine. =(

**Comment by MaxHeadRom** [comment]
Thanks for your assistance. I've just ran System file checker and it reported/ fixed corrupt files. The log file is quite lengthy! I'll restart and test Pyfa again.

**Comment by MaxHeadRom** [comment]
Hey Ryan SFC seems to have zapped that gremlin, I can now merrily click away without crashing. Happy days! Cheers mate.

**Comment by blitzmann** [comment]
wtf I can't believe that worked. Wonderful!

Mind posting the program you used in case others come across the issue? Who knows, it might help folks with the admin privs issue

**Comment by MaxHeadRom** [comment]
I just followed the instructions on this link I found via google pertaining to fixing registry files, it advises the use of the Windows system app SFC which I've never heard of. It did wonders!

http://www.howtogeek.com/222532/how-to-repair-corrupted-windows-system-files-with-the-sfc-and-dism-commands/

Cheers man!

**Comment by blitzmann** [comment]
Ah, SFC was advised somewhere in this thread as well. Doesn't help the folks who are having the admin privs though, but I'm glad it worked for you. =)

**Comment by bosonn** [comment]
I have the same issue as @MaxHeadRom on windows 10 and on a diff 8.1 pc.  sfc did not resolve issue.

  Application Name:	pyfa.exe
  Fault Module Name:	sqlite3.dll
  Exception Code:	c0000005
  Exception Offset:	000142d6
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	1318
  Additional Information 4:	13181ae637ac2592fac0ca2dd662cdcc

[this resolved my issue on both pc](http://answers.microsoft.com/en-us/windows/forum/windows_7-performance/sqlite3dll-error-every-time-i-start-my-computer/2eebfafe-fb2f-4006-8b42-594f9cef0af0)

**Comment by blitzmann** [comment]
We haven't had a report of crashing since last year - whatever it was seems to have cleared up either with Windows updates or with a subsequent release of pyfa. I am still not sure what caused the requirement for admin rights, and would love to know if anyone is still experiencing that issue or if you can now run without Admin.

Since there hasn't been any activity in this thread for some time now, I'm going to close it. Please feel free to continue to comment if things start acting up again, or if you wish to divulge general information.


Thanks everyone!
